{
    "name": "FarmaOffers Theme",
    "version": "18.0.1.0.0",
    "author": "Rootstack, S.A.",
    "category": "Website",
    "summary": "FarmaOffers custom header, footer, pages, snippets and styles",
    "license": "LGPL-3",
    "depends": [
        "website",
        "website_sale",
        "web_editor",
        "theme_grocery",
        "farmaoffers_design",
    ],
    "data": [
        "views/homepage.xml",
        "views/header.xml",
        "views/footer.xml",
        "views/prescription_page.xml",
        "views/contact_page.xml",
        "views/thanks_page.xml",
        "views/snippets.xml",
        "views/quote_page.xml",
        "views/offers_page.xml",
        "views/categories_menu.xml",
        "views/mobile_categories_menu.xml",
        "views/snippets/top_offers_banner_snippet.xml",
        "views/snippets/accordion_snippet.xml",
        "views/snippets/section_faqs_snippet.xml",
        "views/snippets/client_reviews_snippet.xml",
        "views/snippets/top_offers_snippet.xml",
        "views/snippets/owl_carousel_snippet.xml",
        "views/snippets/stripe_info_snippet.xml",
        "views/snippets/select_body_item_snippet.xml",
        "views/snippets/top_products_snippet.xml",
        "views/snippets/body_categories_snippet.xml",
        "views/snippets/our_tips_snippet.xml",
        "views/snippets/card_client_reviews_snippet.xml",
        "views/snippets/card_our_tips_snippet.xml",
        "views/snippets/card_top_offer_snippet.xml",
        "views/snippets/prescription_form_snippet.xml",
        "views/snippets/contact_form_snippet.xml",
        "views/snippets/quote_form_snippet.xml",
        "views/snippets/section_banner_snippet.xml",
        "views/shop_templates.xml",
        "views/web_login.xml",
        "views/web_signup.xml",
        "views/auth_signup_fields.xml",
        "views/web_reset_password.xml",
        "views/web_sale_shop.xml",
        "views/web_product_page.xml",
        "views/breadcrumb.xml",
        "views/checkout_address_required.xml",
        "views/sections/section_general_info.xml",
        "views/sections/section_product_resume.xml",
        "views/sections/section_desc_disc.xml",
        "views/sections/section_additional_info.xml",
        "views/sections/section_same_compound.xml",
        "views/sections/section_bought_together.xml",
        "views/sections/section_faqs.xml",
        "views/checkout_pickup.xml",
    ],
    "assets": {
        "web._assets_primary_variables": [
            "farmaoffers_theme/static/src/scss/farmaoffers_variables.scss",
        ],
        "web.assets_frontend": [
            "farmaoffers_theme/static/src/css/website_sale.css",
            "farmaoffers_theme/static/src/css/splide/splide.min.css",
            "farmaoffers_theme/static/src/js/splide/splide.min.js",
            "farmaoffers_theme/static/src/scss/farmaoffers_styles.scss",
            "farmaoffers_theme/static/src/scss/farmaoffers_top_header.scss",
            "farmaoffers_theme/static/src/scss/styles.scss",
            "farmaoffers_theme/static/src/snippets/t_owl_carousel/style.scss",
            "farmaoffers_theme/static/src/snippets/t_owl_carousel/000.js",
            # "farmaoffers_theme/static/src/js/checkout_address_state_required.js",
            "farmaoffers_theme/static/src/js/checkout_pickup_toggle.js",
            "farmaoffers_theme/static/src/js/mobile_menu.js",
            "farmaoffers_theme/static/src/js/cart_total_sync.js",
        ],
    },
    "installable": True,
    "application": False,
}
