{
    "name": "Theme Grocery",
    "version": "18.0.0.1",
    "summary": "Ecommerce theme for grocery/food stores.",
    "description": "Online Supermarket theme.",
    "license": "OPL-1",
    "author": "Kanak Infosystems LLP.",
    "category": "Theme/Website",
    "depends": [
        "website",
        "website_sale",
        "website_sale_wishlist",
        "website_sale_comparison",
        "website_mass_mailing",
        "mass_mailing",
        "website_blog"
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/views.xml",
        "views/customize_show_templates.xml",
        "views/h_f_templates.xml",
        "views/homepage_templates.xml",
        "views/shop_templates.xml",
        "views/product_details_templates.xml",
        "views/snippets.xml",
    ],
    "demo": ["demo/theme_grocery_demo.xml"],
    "installable": True,
    "application": True,
    "images": [
        "static/description/theme_grocery.jpg",
        "static/description/theme_grocery_screenshot.jpg",
    ],
}
