{
    "name": "FarmaOffers Module",
    "version": "18.0.1.0.0",
    "author": "Rootstack, S.A.",
    "category": "Website",
    "summary": "Core models and helpers for FarmaOffers website",
    "license": "LGPL-3",
    "depends": [
        "web",
        "website",
        "web_editor",
        "website_sale",
        "sale_management",
        "sale_stock",
        "stock",
        "product",
        "auth_signup",
        "point_of_sale",
        "theme_grocery",
        "multi_branch",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/fo_top_slider_views.xml",
        "views/product_offers_views.xml",
        "views/top_products_views.xml",
        "views/our_tips_views.xml",
        "views/client_reviews_views.xml",
        "views/faqs_views.xml",
        "views/prescription_views.xml",
        "views/quote_view.xml",
        "views/branch_offices_views.xml",
        "views/contact_views.xml",
        "views/menus.xml",
        "views/account_move_view.xml",
        "views/stock_picking_view.xml",
        "views/sale_order.xml",
        "views/pos_config_view.xml",
        "views/multi_branch_extension_view.xml",
        "views/sales_report_view.xml",
    ],
    "installable": True,
    "application": False,
}
